### ISSUE TITLE
Provide platform version from `/version` endpoint

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/rest-api#131] opened 2021-05-11 05:10 UTC
Currently the [version endpoint](https://github.com/PlaceOS/rest-api/blob/ce3f31cf24079942e534acebe623810627d516c5/src/placeos-rest-api/controllers/root.cr#L65-L72) provides semver information for the `rest-api` service. Release builds will also reference the commit hash from the [release repo](https://github.com/PlaceOS/PlaceOS/blob/40306d783bcfa7e524211673d9664b04c015cc4c/.github/workflows/build.yml#L95).

This information forms the version information shown in Backoffice.
![18CC7D7C-881D-45DD-A8CB-9BBE249E0076](https://user-images.githubusercontent.com/843652/117761034-01b74e80-b26a-11eb-90ab-e64dedba761f.png)

As this is the main visible version identifier for external users, to remove the need for manual lookups and confusion around multiple versioning schemes it may be cleaner to provide platform versions here. Information for this is currently [encoded in an image label](https://github.com/PlaceOS/PlaceOS/blob/40306d783bcfa7e524211673d9664b04c015cc4c/.github/workflows/build.yml#L104), but could also be placed into an ENV var for simpler access.

If there is a desire / need to keep the existing version endpoint for service information, it would be useful to implement a `/platform-info` or similar endpoint with this information.

**Comment by caspiano** [comment] 2021-05-11 06:06
duplicate of #82

**Comment by caspiano** [comment] 2021-06-09 02:43
Closed by 773a4d55bf3c51924fdb07ef2f0c479c58f80781

**Closed** 2021-06-10 11:30 UTC
Labels: type: enhancement
