### ISSUE TITLE
Metadata searches do not adhere to `limit` param (and probably offset param too)

### ISSUE THREAD

**Issue by w-le** [PlaceOS/rest-api#268] opened 2022-04-27 04:47 UTC
**Describe the bug**
When searching metadata with `limit=1` we get >1 result

**Your environment**
placeos-2204.2-rc4

**To Reproduce**
See API request and params in screenshot below

**Expected behavior**
Response should have had 1 metadata result, since param `limit=1` was present
 
**Screenshots**
Done with placeos-2204.2-rc4
![image](https://user-images.githubusercontent.com/10395560/165442738-040a7f55-3da5-4d3e-a4f1-1ec0e7ab512a.png)

**Comment by caspiano** [comment] 2022-04-27 04:59
Duplicate of https://github.com/PlaceOS/rest-api/issues/263

**Closed by caspiano** 2022-04-27 04:59 UTC
Labels: focus: backend, priority: medium, type: bug
